(ns flechar.ui.root
  (:require
    [fulcro.client.dom :as dom]
    [fulcro.client.primitives :as prim]
    [flechar.model.user :as user]
    [flechar.ui.components :as comp]
    [flechar.ui.user-comp :as fuc]
    [taoensso.timbre :as log]))


(prim/defsc Root [this {:keys [all-users]}]
  {:query         [{:all-users (prim/get-query fuc/User)}]
   :initial-state {:all-users []}}
  (dom/div :.ui.segments
    (dom/div :.ui.top.attached.segment
      (dom/h3 :.ui.header
        "Welcome to Fulcro!")
      (dom/p
        "This is full-stack demo content that shows off some of the dom/power of Pathom when used with Fulcro. "
        "The 'add user' button will randomly generate a user's id/name, and transact it with the server via a mutation join. "
        "The mutation join returns the newly created user with additional autogenerated server details (in this case address info). "
        "A mutation join is a transaction that can read after writing. ")
      (dom/p
        "The resolvers and mutations are in model/user.clj(s). "
        "The UI will query for all users on start, so after you
        add some, be sure to reload the page and see it come back.")
      (dom/p
        "Make sure you've installed Fulcro Inspect, and your Chrome devtools will let you examine all of the details
        of the running flechar!")
             (comp/ui-placeholder {:w 50 :h 50 :label "avatar"}))
    (dom/div :.ui.attached.segment
      (dom/div :.content
               (dom/div "Your system has the following users in the database:")
               (dom/ul :.ui.list
                       (map fuc/ui-user all-users))
               (fuc/ui-user-button {:w 50 :h 50 :label "avatar"})))))
